//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EeveexModManager
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpgraded
        {
            get
            {
                return ((bool)(this["SettingsUpgraded"]));
            }
            set
            {
                this["SettingsUpgraded"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InstalledGamesDetected
        {
            get
            {
                return ((bool)(this["InstalledGamesDetected"]));
            }
            set
            {
                this["InstalledGamesDetected"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberedGameMode
        {
            get
            {
                return ((string)(this["RememberedGameMode"]));
            }
            set
            {
                this["RememberedGameMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ultra")]
        public global::SevenZip.CompressionLevel ModCompressionLevel
        {
            get
            {
                return ((global::SevenZip.CompressionLevel)(this["ModCompressionLevel"]));
            }
            set
            {
                this["ModCompressionLevel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SevenZip")]
        public global::SevenZip.OutArchiveFormat ModCompressionFormat
        {
            get
            {
                return ((global::SevenZip.OutArchiveFormat)(this["ModCompressionFormat"]));
            }
            set
            {
                this["ModCompressionFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedAddModCommandIndex
        {
            get
            {
                return ((int)(this["SelectedAddModCommandIndex"]));
            }
            set
            {
                this["SelectedAddModCommandIndex"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForNewModVersions
        {
            get
            {
                return ((bool)(this["CheckForNewModVersions"]));
            }
            set
            {
                this["CheckForNewModVersions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddMissingInfoToMods
        {
            get
            {
                return ((bool)(this["AddMissingInfoToMods"]));
            }
            set
            {
                this["AddMissingInfoToMods"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseModManagerAfterGameLaunch
        {
            get
            {
                return ((bool)(this["CloseModManagerAfterGameLaunch"]));
            }
            set
            {
                this["CloseModManagerAfterGameLaunch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseModManagerAfterGameLaunchIsRemembered
        {
            get
            {
                return ((bool)(this["CloseModManagerAfterGameLaunchIsRemembered"]));
            }
            set
            {
                this["CloseModManagerAfterGameLaunchIsRemembered"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RememberGameMode
        {
            get
            {
                return ((bool)(this["RememberGameMode"]));
            }
            set
            {
                this["RememberGameMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanSubfoldersForMods
        {
            get
            {
                return ((bool)(this["ScanSubfoldersForMods"]));
            }
            set
            {
                this["ScanSubfoldersForMods"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdatesOnStartup
        {
            get
            {
                return ((bool)(this["CheckForUpdatesOnStartup"]));
            }
            set
            {
                this["CheckForUpdatesOnStartup"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.nexusmods.com/content/modmanager/")]
        public string ModManagerUrl
        {
            get
            {
                return ((string)(this["ModManagerUrl"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string UserLocation
        {
            get
            {
                return ((string)(this["UserLocation"]));
            }
            set
            {
                this["UserLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMultithreadedDownloads
        {
            get
            {
                return ((bool)(this["UseMultithreadedDownloads"]));
            }
            set
            {
                this["UseMultithreadedDownloads"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int UpdateCheckInterval
        {
            get
            {
                return ((int)(this["UpdateCheckInterval"]));
            }
            set
            {
                this["UpdateCheckInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUpdateCheckDate
        {
            get
            {
                return ((string)(this["LastUpdateCheckDate"]));
            }
            set
            {
                this["LastUpdateCheckDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ModVersionsCheckInterval
        {
            get
            {
                return ((int)(this["ModVersionsCheckInterval"]));
            }
            set
            {
                this["ModVersionsCheckInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastModVersionsCheckDate
        {
            get
            {
                return ((string)(this["LastModVersionsCheckDate"]));
            }
            set
            {
                this["LastModVersionsCheckDate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempPathFolder
        {
            get
            {
                return ((string)(this["TempPathFolder"]));
            }
            set
            {
                this["TempPathFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TraceLogFolder
        {
            get
            {
                return ((string)(this["TraceLogFolder"]));
            }
            set
            {
                this["TraceLogFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExpandedCategories
        {
            get
            {
                return ((bool)(this["ShowExpandedCategories"]));
            }
            set
            {
                this["ShowExpandedCategories"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEmptyCategory
        {
            get
            {
                return ((bool)(this["ShowEmptyCategory"]));
            }
            set
            {
                this["ShowEmptyCategory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideModUpdateWarningIcon
        {
            get
            {
                return ((bool)(this["HideModUpdateWarningIcon"]));
            }
            set
            {
                this["HideModUpdateWarningIcon"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SkipReadmeFiles
        {
            get
            {
                return ((bool)(this["SkipReadmeFiles"]));
            }
            set
            {
                this["SkipReadmeFiles"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSidePanel
        {
            get
            {
                return ((bool)(this["ShowSidePanel"]));
            }
            set
            {
                this["ShowSidePanel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CategoryViewDefaultSortOrder
        {
            get
            {
                return ((int)(this["CategoryViewDefaultSortOrder"]));
            }
            set
            {
                this["CategoryViewDefaultSortOrder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CategoryViewDefaultSortColumn
        {
            get
            {
                return ((int)(this["CategoryViewDefaultSortColumn"]));
            }
            set
            {
                this["CategoryViewDefaultSortColumn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCategoryView
        {
            get
            {
                return ((bool)(this["UseCategoryView"]));
            }
            set
            {
                this["UseCategoryView"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OfflineMode
        {
            get
            {
                return ((bool)(this["OfflineMode"]));
            }
            set
            {
                this["OfflineMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SupportOfflineMode
        {
            get
            {
                return ((bool)(this["SupportOfflineMode"]));
            }
            set
            {
                this["SupportOfflineMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStartupMessage
        {
            get
            {
                return ((bool)(this["ShowStartupMessage"]));
            }
            set
            {
                this["ShowStartupMessage"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForTipsOnStartup
        {
            get
            {
                return ((bool)(this["CheckForTipsOnStartup"]));
            }
            set
            {
                this["CheckForTipsOnStartup"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
     <KeyedSettingsOfString>
      <item key=""Beta Wiki"">
       <string>http://wiki.nexusmods.com/index.php/Category:NMM</string>
      </item>
      <item key=""Beta Forums"">
       <string>http://forums.nexusmods.com/index.php?/forum/439-open-beta-feedback/</string>
      </item>
      <item key=""Bug Report How To"">
       <string>http://forums.nexusmods.com/index.php?/topic/460590-reporting-bugs/</string>
      </item>
      <item key=""Report a Bug"">
       <string>http://forums.nexusmods.com/index.php?/tracker/project-3-mod-manager-open-beta/</string>
      </item>
     </KeyedSettingsOfString>
    ")]
        public global::EeveexModManager.KeyedSettings<string> HelpLinks
        {
            get
            {
                return ((global::EeveexModManager.KeyedSettings<string>)(this["HelpLinks"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<string> ExecutablePaths
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<string>)(this["ExecutablePaths"]));
            }
            set
            {
                this["ExecutablePaths"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<string> InstallationPaths
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<string>)(this["InstallationPaths"]));
            }
            set
            {
                this["InstallationPaths"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfBoolean />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<bool> CompletedSetup
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<bool>)(this["CompletedSetup"]));
            }
            set
            {
                this["CompletedSetup"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<string> ModFolder
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<string>)(this["ModFolder"]));
            }
            set
            {
                this["ModFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfPerGameModeSettingsOfObject />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<EeveexModManager.PerGameModeSettings<object>> CustomGameModeSettings
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<EeveexModManager.PerGameModeSettings<object>>)(this["CustomGameModeSettings"]));
            }
            set
            {
                this["CustomGameModeSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<string> InstallInfoFolder
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<string>)(this["InstallInfoFolder"]));
            }
            set
            {
                this["InstallInfoFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <KeyedSettingsOfString />\r\n    ")]
        public global::EeveexModManager.KeyedSettings<string> DockPanelLayouts
        {
            get
            {
                return ((global::EeveexModManager.KeyedSettings<string>)(this["DockPanelLayouts"]));
            }
            set
            {
                this["DockPanelLayouts"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<string> CustomLaunchCommands
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<string>)(this["CustomLaunchCommands"]));
            }
            set
            {
                this["CustomLaunchCommands"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<string> CustomLaunchCommandArguments
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<string>)(this["CustomLaunchCommandArguments"]));
            }
            set
            {
                this["CustomLaunchCommandArguments"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<string> SelectedLaunchCommands
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<string>)(this["SelectedLaunchCommands"]));
            }
            set
            {
                this["SelectedLaunchCommands"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <KeyedSettingsOfString />\r\n    ")]
        public global::EeveexModManager.KeyedSettings<string> RepositoryUsernames
        {
            get
            {
                return ((global::EeveexModManager.KeyedSettings<string>)(this["RepositoryUsernames"]));
            }
            set
            {
                this["RepositoryUsernames"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <KeyedSettingsOfKeyedSettingsOfString />\r\n    ")]
        public global::EeveexModManager.KeyedSettings<EeveexModManager.KeyedSettings<string>> RepositoryAuthenticationTokens
        {
            get
            {
                return ((global::EeveexModManager.KeyedSettings<EeveexModManager.KeyedSettings<string>>)(this["RepositoryAuthenticationTokens"]));
            }
            set
            {
                this["RepositoryAuthenticationTokens"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <PerGameModeSettingsOfKeyedSettingsOfString />\r\n    ")]
        public global::EeveexModManager.PerGameModeSettings<EeveexModManager.KeyedSettings<string>> DelayedSettings
        {
            get
            {
                return ((global::EeveexModManager.PerGameModeSettings<EeveexModManager.KeyedSettings<string>>)(this["DelayedSettings"]));
            }
            set
            {
                this["DelayedSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n     <ArrayOfString xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns" +
            ":xsd=\"http://www.w3.org/2001/XMLSchema\" />\r\n    ")]
        public global::EeveexModManager.SettingsList InstalledGames
        {
            get
            {
                return ((global::EeveexModManager.SettingsList)(this["InstalledGames"]));
            }
            set
            {
                this["InstalledGames"] = value;
            }
        }

    }
}
